// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: service.proto
// </auto-generated>
#pragma warning disable 1591
#region Designer generated code

using System;
using System.Threading;
using System.Threading.Tasks;
using grpc = global::Grpc.Core;

namespace Example {
  public static partial class ExampleService
  {
    static readonly string __ServiceName = "Example.ExampleService";

    static readonly grpc::Marshaller<global::Example.AddUserArgs> __Marshaller_AddUserArgs = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Example.AddUserArgs.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Example.AddUserReply> __Marshaller_AddUserReply = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Example.AddUserReply.Parser.ParseFrom);

    static readonly grpc::Method<global::Example.AddUserArgs, global::Example.AddUserReply> __Method_AddUser = new grpc::Method<global::Example.AddUserArgs, global::Example.AddUserReply>(
        grpc::MethodType.Unary,
        __ServiceName,
        "AddUser",
        __Marshaller_AddUserArgs,
        __Marshaller_AddUserReply);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Example.ServiceReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of ExampleService</summary>
    public abstract partial class ExampleServiceBase
    {
      public virtual global::System.Threading.Tasks.Task<global::Example.AddUserReply> AddUser(global::Example.AddUserArgs request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for ExampleService</summary>
    public partial class ExampleServiceClient : grpc::ClientBase<ExampleServiceClient>
    {
      /// <summary>Creates a new client for ExampleService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public ExampleServiceClient(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for ExampleService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public ExampleServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected ExampleServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected ExampleServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::Example.AddUserReply AddUser(global::Example.AddUserArgs request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return AddUser(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Example.AddUserReply AddUser(global::Example.AddUserArgs request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_AddUser, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Example.AddUserReply> AddUserAsync(global::Example.AddUserArgs request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return AddUserAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Example.AddUserReply> AddUserAsync(global::Example.AddUserArgs request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_AddUser, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override ExampleServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new ExampleServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(ExampleServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_AddUser, serviceImpl.AddUser).Build();
    }

  }
}
#endregion
